package com.rjxz.xykd.bean;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activities
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Activities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.time
     *
     * @mbg.generated
     */
    private LocalDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.activity
     *
     * @mbg.generated
     */
    private String activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.id
     *
     * @return the value of activities.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.id
     *
     * @param id the value for activities.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.userId
     *
     * @return the value of activities.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.userId
     *
     * @param userid the value for activities.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.time
     *
     * @return the value of activities.time
     *
     * @mbg.generated
     */
    public LocalDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.time
     *
     * @param time the value for activities.time
     *
     * @mbg.generated
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.activity
     *
     * @return the value of activities.activity
     *
     * @mbg.generated
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.activity
     *
     * @param activity the value for activities.activity
     *
     * @mbg.generated
     */
    public void setActivity(String activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.type
     *
     * @return the value of activities.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.type
     *
     * @param type the value for activities.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}